name: Build UWP App

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore SimpliPlay/SimpliPlay/SimpliPlay.sln

    - name: Upgrade Chocolatey (to latest)
      shell: pwsh
      run: choco upgrade chocolatey -y

    - name: Install Windows 10 SDK (latest 10.x)
      shell: pwsh
      run: |
        if (-not (choco list --localonly | Select-String 'windows-sdk-10.0')) {
          choco install windows-sdk-10.0 -y
        } else {
          Write-Host "Windows SDK 10.0 already installed."
        }

    - name: Install Windows 10 SDK Developer Pack (10.0.26624)
      shell: pwsh
      run: |
        $url = "https://go.microsoft.com/fwlink/p/?LinkId=619296"
        $installer = "$env:TEMP\winsdksetup.exe"
        Invoke-WebRequest -Uri $url -OutFile $installer
        Start-Process -FilePath $installer -ArgumentList '/quiet', '/norestart' -Wait
        Remove-Item $installer

          
    - name: Install Visual Studio 2022 .NET SDK
      shell: pwsh
      run: |
        $url = "https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.301/dotnet-sdk-9.0.301-win-x86.exe"
        $installer = "$env:TEMP\dotnet-sdk-9.0.301-win-x86.exe"
        Invoke-WebRequest -Uri $url -OutFile $installer
        Start-Process -FilePath $installer -ArgumentList '/quiet', '/norestart' -Wait
        Remove-Item $installer



    - name: Install UWP Build Tools workload
      shell: pwsh
      run: |
        if (-not (choco list --localonly | Select-String 'visualstudio2022-workload-universal')) {
          choco install visualstudio2022-workload-universal --no-progress -y
        } else {
          Write-Host "UWP workload already installed."
        }

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build UWP solution and create app package
      shell: cmd
      run: msbuild SimpliPlay/SimpliPlay/SimpliPlay.sln /p:Configuration=Debug /p:Platform=x86

    - name: Publish app package artifact
      uses: actions/upload-artifact@v4
      with:
        name: uwp-package
        path: SimpliPlay/SimpliPlay/bin/x86/Debug/AppPackages/
