name: Build UWP App

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore SimpliPlay.sln

    - name: Build UWP solution and create app package
      run: msbuild SimpliPlay.sln /p:Configuration=Release /p:Platform=x86 /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload

    - name: Publish app package artifact
      uses: actions/upload-artifact@v4
      with:
        name: uwp-package
        path: SimpliPlay\bin\x86\Release\AppPackages\
