name: Build UWP App

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore SimpliPlay/SimpliPlay/SimpliPlay.sln

    - name: Upgrade Chocolatey (to latest)
      shell: pwsh
      run: choco upgrade chocolatey -y

    - name: Install Windows 10 SDK (latest 10.x)
      shell: pwsh
      run: |
        if (-not (choco list --localonly | Select-String 'windows-sdk-10.0')) {
          choco install windows-sdk-10.0 -y
        } else {
          Write-Host "Windows SDK 10.0 already installed."
        }

    - name: Install UWP Build Tools workload
      shell: pwsh
      run: |
        if (-not (choco list --localonly | Select-String 'visualstudio2022-workload-universal')) {
          choco install visualstudio2022-workload-universal --no-progress -y
        } else {
          Write-Host "UWP workload already installed."
        }

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build UWP solution and create app package
      shell: cmd
      run: msbuild SimpliPlay/SimpliPlay/SimpliPlay.sln /p:Configuration=Release /p:Platform=x86 /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload /p:TargetPlatformVersion=10.0.19041.0

    - name: Publish app package artifact
      uses: actions/upload-artifact@v4
      with:
        name: uwp-package
        path: SimpliPlay/SimpliPlay/bin/x86/Release/AppPackages/
